@extends('layouts.app')
@section('title', 'Audit Materi')
@section('content')
<header><p class="text-sm font-semibold text-emerald-700">Pemeriksaan keterlacakan</p><h1 class="mt-1 text-3xl font-semibold text-balance text-slate-950">Audit GGB ke silabus</h1><p class="mt-2 max-w-3xl text-pretty text-slate-600">Status menunjukkan tingkat kecocokan teks awal. Materi yang perlu diperiksa tetap tersimpan beserta kedua halaman sumber.</p></header>
<section class="mt-7 grid gap-4 sm:grid-cols-3">
    <article class="panel p-5"><p class="text-sm text-slate-500">Sesuai</p><p class="metric-number mt-2 text-emerald-800">{{ number_format($statusCounts['sesuai'] ?? 0) }}</p></article>
    <article class="panel p-5"><p class="text-sm text-slate-500">Sebagian</p><p class="metric-number mt-2 text-amber-700">{{ number_format($statusCounts['sebagian'] ?? 0) }}</p></article>
    <article class="panel p-5"><p class="text-sm text-slate-500">Perlu verifikasi</p><p class="metric-number mt-2 text-red-700">{{ number_format($statusCounts['perlu_verifikasi'] ?? 0) }}</p></article>
</section>
<section class="panel mt-6 p-5"><h2 class="text-lg font-semibold text-slate-950">Indikator per jenjang</h2><div class="mt-4 grid gap-3 lg:grid-cols-2">@forelse($findings as $finding)<div class="rounded-xl bg-slate-50 p-4 ring-1 ring-slate-200"><div class="flex items-center justify-between gap-3"><p class="font-semibold text-slate-900">{{ $finding->level?->name ?? 'Semua jenjang' }}</p><span class="status {{ $finding->severity === 'warning' ? 'status-warning' : 'status-neutral' }}">{{ ucfirst($finding->severity) }}</span></div><p class="mt-2 text-sm text-pretty text-slate-600">{{ $finding->message }}</p></div>@empty<p class="text-slate-500">Tidak ada temuan terbuka.</p>@endforelse</div></section>
<section class="panel mt-6 overflow-hidden"><div class="border-b border-slate-200 px-5 py-4"><h2 class="text-lg font-semibold text-slate-950">Relasi yang perlu ditinjau</h2></div><div class="overflow-x-auto"><table class="data-table"><thead><tr><th>Jenjang</th><th>Silabus</th><th>Calon GGB</th><th>Status</th><th>Skor</th></tr></thead><tbody>@foreach($links as $link)<tr><td class="font-semibold text-slate-950">{{ $link->level_name }}</td><td class="min-w-80">{{ $link->syllabus_title }}<p class="mt-1 text-xs text-slate-500">Silabus hlm. {{ $link->syllabus_page }}</p></td><td class="min-w-80">{{ $link->ggb_title }}<p class="mt-1 text-xs text-slate-500">GGB hlm. {{ $link->ggb_page }}</p></td><td><span class="status {{ $link->status === 'sebagian' ? 'status-warning' : 'status-danger' }}">{{ str_replace('_', ' ', ucfirst($link->status)) }}</span></td><td class="font-mono tabular-nums">{{ number_format($link->confidence * 100, 1) }}%</td></tr>@endforeach</tbody></table></div><div class="border-t border-slate-200 px-4 py-3">{{ $links->links() }}</div></section>
@endsection
