<div>
    <header><p class="text-sm font-semibold text-emerald-700">{{ $year->label }}</p><h1 class="mt-1 text-3xl font-semibold text-balance text-slate-950">Kalender akademik mingguan</h1><p class="mt-2 max-w-3xl text-pretty text-slate-600">Tanggal dimulai 6 Juli 2026. Ubah jenis minggu sebelum memvalidasi RPP.</p></header>
    @if($notice)<div class="mt-5 rounded-xl bg-emerald-50 px-4 py-3 text-sm text-emerald-900 ring-1 ring-emerald-200" role="status">{{ $notice }}</div>@endif
    <section class="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4" aria-label="Legenda kalender">
        <div class="rounded-xl bg-white p-4 ring-1 ring-emerald-200"><p class="font-semibold text-emerald-800">Minggu Efektif</p><p class="mt-1 text-sm text-slate-500">Dapat menerima materi.</p></div>
        <div class="rounded-xl bg-white p-4 ring-1 ring-amber-200"><p class="font-semibold text-amber-800">Evaluasi</p><p class="mt-1 text-sm text-slate-500">Tidak menerima materi.</p></div>
        <div class="rounded-xl bg-white p-4 ring-1 ring-slate-200"><p class="font-semibold text-slate-700">Libur</p><p class="mt-1 text-sm text-slate-500">Jadwal dikosongkan.</p></div>
        <div class="rounded-xl bg-white p-4 ring-1 ring-red-200"><p class="font-semibold text-red-800">Hari Raya</p><p class="mt-1 text-sm text-slate-500">Jadwal dikosongkan.</p></div>
    </section>
    <section class="panel mt-6 overflow-hidden"><div class="overflow-x-auto"><table class="data-table"><thead><tr><th>Pekan</th><th>Tanggal Mulai</th><th>Bulan</th><th>Jenis Minggu</th><th>Materi Terpasang</th></tr></thead><tbody>@foreach($weeks as $week)<tr wire:key="week-{{ $week->id }}"><td class="font-mono font-semibold tabular-nums">M{{ $week->week_number }}</td><td>{{ $week->starts_on->translatedFormat('d F Y') }}</td><td>{{ $week->month_label }}</td><td><select wire:change="setType({{ $week->id }}, $event.target.value)" class="min-h-11 rounded-xl border border-slate-300 bg-white px-3 text-sm" aria-label="Jenis minggu {{ $week->week_number }}"><option value="effective" @selected($week->type === 'effective')>Minggu Efektif</option><option value="evaluation" @selected($week->type === 'evaluation')>Evaluasi</option><option value="holiday" @selected($week->type === 'holiday')>Libur</option><option value="religious_holiday" @selected($week->type === 'religious_holiday')>Hari Raya</option></select></td><td class="font-mono tabular-nums">{{ $week->placements_count }}</td></tr>@endforeach</tbody></table></div></section>
</div>
