<div>
    <header class="flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between"><div><a href="{{ route('dashboard') }}" class="text-sm font-semibold text-emerald-700">Dashboard</a><h1 class="mt-2 text-3xl font-semibold text-balance text-slate-950">RPP mingguan {{ $level->name }}</h1><p class="mt-2 max-w-3xl text-pretty text-slate-600">Draf otomatis mengikuti urutan silabus dan hanya menggunakan minggu efektif. Materi manual yang dikunci tidak berubah saat disusun ulang.</p></div><div class="flex flex-wrap gap-2"><button wire:click="generateAll" wire:loading.attr="disabled" class="button-secondary">Susun Semua Kelas</button><button wire:click="generate" wire:loading.attr="disabled" class="button-primary">Susun {{ $level->name }}</button><button wire:click="validatePlan" wire:loading.attr="disabled" class="button-secondary">Validasi</button></div></header>
    @if($notice)<div class="mt-5 rounded-xl bg-emerald-50 px-4 py-3 text-sm text-emerald-900 ring-1 ring-emerald-200" role="status">{{ $notice }}</div>@endif
    <section class="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><article class="panel p-5"><p class="text-sm text-slate-500">Cakupan</p><p class="metric-number mt-2">{{ number_format((float)$plan->coverage_percent, 1) }}%</p></article><article class="panel p-5"><p class="text-sm text-slate-500">Belum dijadwalkan</p><p class="metric-number mt-2 {{ $unplanned ? 'text-red-700' : 'text-emerald-800' }}">{{ $unplanned }}</p></article><article class="panel p-5"><p class="text-sm text-slate-500">Perlu alokasi</p><p class="metric-number mt-2 text-amber-700">{{ $needsAllocation }}</p></article><article class="panel p-5"><p class="text-sm text-slate-500">Status</p><p class="mt-3"><span class="status {{ $plan->status === 'validated' ? 'status-success' : 'status-warning' }}">{{ $plan->status === 'validated' ? 'Tervalidasi' : 'Draf' }}</span></p></article></section>
    <section class="panel mt-6 p-4"><h2 class="font-semibold text-slate-950">Bantuan cepat</h2><div class="mt-3 flex flex-wrap gap-2"><button wire:click="fillEmpty" class="button-secondary">Isi Minggu Kosong</button><button wire:click="rebalance" class="button-secondary">Ratakan Beban</button><button wire:click="restartFromSyllabus" class="button-secondary">Ulangi dari Silabus</button></div><p class="mt-3 text-sm text-slate-500">Tindakan menyusun ulang bagian otomatis secara deterministik. Materi duplikat dan yang berstatus Perlu Alokasi tidak dipaksakan masuk; baris terkunci tetap aman.</p></section>
    <section class="mt-6 space-y-3">
    @foreach($weeks as $week)
        @php($weekItems = collect($itemsByWeek->get($week->id, [])))
        <article class="panel overflow-hidden {{ $week->is_effective ? '' : 'bg-slate-100' }}" wire:key="planner-week-{{ $week->id }}"><div class="flex flex-col gap-2 border-b border-slate-200 px-4 py-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 class="font-semibold text-slate-950">M{{ $week->week_number }} · {{ $week->starts_on->translatedFormat('d F Y') }}</h2><p class="text-sm text-slate-500">{{ $week->month_label }}</p></div><span class="status {{ $week->is_effective ? 'status-success' : 'status-neutral' }}">{{ $week->is_effective ? 'Minggu Efektif' : str_replace('_', ' ', ucfirst($week->type)) }}</span></div>
            @if($weekItems->isEmpty())<div class="p-4"><p class="text-sm text-slate-500">{{ $week->is_effective ? 'Belum ada materi pada minggu ini.' : 'Minggu ini tidak menerima materi.' }}</p></div>@else<div class="divide-y divide-slate-100">@foreach($weekItems as $item)<div class="grid gap-3 p-4 lg:grid-cols-[180px_1fr_190px_110px] lg:items-center" wire:key="placement-{{ $item->id }}"><div><p class="font-semibold text-slate-900">{{ $item->strand }}</p><span class="status {{ $item->is_locked ? 'status-warning' : 'status-neutral' }} mt-1">{{ $item->is_locked ? 'Terkunci' : 'Otomatis' }}</span></div><p class="text-sm text-pretty text-slate-700">{{ $item->content }}</p><select wire:change="movePlacement({{ $item->id }}, $event.target.value)" class="min-h-11 rounded-xl border border-slate-300 bg-white px-3 text-sm" aria-label="Pindahkan {{ $item->content }}"><option value="">Pindahkan ke...</option>@foreach($weeks->where('is_effective', true) as $target)<option value="{{ $target->id }}" @selected($target->id === $week->id)>M{{ $target->week_number }} · {{ $target->starts_on->format('d/m') }}</option>@endforeach</select><button wire:click="toggleLock({{ $item->id }})" class="button-secondary">{{ $item->is_locked ? 'Buka Kunci' : 'Kunci' }}</button></div>@endforeach</div>@endif
        </article>
    @endforeach
    </section>
</div>
