<section id="calendar-detail" class="panel scroll-mt-4 overflow-hidden" aria-labelledby="calendar-detail-title">
    <div class="flex flex-col gap-3 border-b border-slate-200 p-4 sm:flex-row sm:items-start sm:justify-between sm:p-5">
        <div><p class="text-sm font-semibold text-emerald-700">Kalender {{ $plan->academicYear->label }}</p><h2 id="calendar-detail-title" class="mt-1 text-xl font-semibold text-slate-950">Atur waktu semester, libur, evaluasi, dan ujian</h2><p class="mt-1 max-w-3xl text-sm text-slate-600">Rentang yang menyentuh sebagian pekan membuat satu pekan penuh non-efektif. Materi bergeser setelah Admin mengonfirmasi dampaknya.</p></div>
        <button type="button" wire:click="showDetail('')" class="button-secondary">Tutup pengaturan</button>
    </div>
    <div class="grid gap-5 p-4 xl:grid-cols-2 sm:p-5">
        <form wire:submit="saveSemesterRanges" class="rounded-xl bg-slate-50 p-4 ring-1 ring-slate-200">
            <h3 class="font-semibold text-slate-950">Rentang semester</h3><p class="mt-1 text-sm text-slate-600">Jumlah minggu dihitung dari tanggal Admin dan tidak lagi dipaksa 26.</p>
            <div class="mt-4 grid gap-3 sm:grid-cols-2">
                <label class="grid gap-1 text-sm font-medium text-slate-700">Mulai Semester 1<input type="date" wire:model="semesterOneStart" class="min-h-11 rounded-xl border border-slate-300 bg-white px-3"></label><label class="grid gap-1 text-sm font-medium text-slate-700">Akhir Semester 1<input type="date" wire:model="semesterOneEnd" class="min-h-11 rounded-xl border border-slate-300 bg-white px-3"></label><label class="grid gap-1 text-sm font-medium text-slate-700">Mulai Semester 2<input type="date" wire:model="semesterTwoStart" class="min-h-11 rounded-xl border border-slate-300 bg-white px-3"></label><label class="grid gap-1 text-sm font-medium text-slate-700">Akhir Semester 2<input type="date" wire:model="semesterTwoEnd" class="min-h-11 rounded-xl border border-slate-300 bg-white px-3"></label>
            </div><button type="submit" wire:loading.attr="disabled" class="button-secondary mt-4">Simpan rentang semester</button>
        </form>
        <form wire:submit="saveCalendarEvent" class="rounded-xl bg-white p-4 ring-1 ring-slate-200">
            <div class="flex items-center justify-between gap-3"><h3 class="font-semibold text-slate-950">{{ $calendarEventId ? 'Edit' : 'Tambah' }} rentang kegiatan</h3>@if($calendarEventId)<button type="button" wire:click="resetCalendarForm" class="min-h-11 text-sm font-semibold text-emerald-700">Batal edit</button>@endif</div>
            <div class="mt-4 grid gap-3 sm:grid-cols-2">
                <label class="grid gap-1 text-sm font-medium text-slate-700">Jenis<select wire:model.live="calendarType" class="min-h-11 rounded-xl border border-slate-300 bg-white px-3"><option value="holiday">Libur</option><option value="religious_holiday">Hari Raya</option><option value="evaluation">Evaluasi</option><option value="exam">Ujian</option></select></label><label class="grid gap-1 text-sm font-medium text-slate-700">Judul<input type="text" wire:model.live.debounce.250ms="calendarTitle" class="min-h-11 rounded-xl border border-slate-300 bg-white px-3" placeholder="Contoh: Ujian semester serentak"></label><label class="grid gap-1 text-sm font-medium text-slate-700">Tanggal mulai<input type="date" wire:model.live="calendarStartsOn" class="min-h-11 rounded-xl border border-slate-300 bg-white px-3"></label><label class="grid gap-1 text-sm font-medium text-slate-700">Tanggal akhir<input type="date" wire:model.live="calendarEndsOn" class="min-h-11 rounded-xl border border-slate-300 bg-white px-3"></label><label class="grid gap-1 text-sm font-medium text-slate-700 sm:col-span-2">Keterangan detail<textarea wire:model.live.debounce.250ms="calendarDetails" rows="3" class="rounded-xl border border-slate-300 bg-white px-3 py-2" placeholder="Keterangan yang akan tampil pada preview dan Excel"></textarea></label>
            </div>
            <label class="mt-3 flex min-h-11 items-center gap-3 rounded-xl border border-slate-200 px-3"><input type="checkbox" wire:model.live="calendarAllLevels" class="size-5 rounded border-slate-300 text-emerald-700"><span class="text-sm font-medium text-slate-700">Berlaku untuk semua jenjang</span></label>
            @if(! $calendarAllLevels)<fieldset class="mt-3"><legend class="text-sm font-medium text-slate-700">Pilih jenjang</legend><div class="mt-2 grid max-h-44 gap-1 overflow-y-auto rounded-xl border border-slate-200 p-2 sm:grid-cols-2">@foreach($levels as $level)<label class="flex min-h-11 items-center gap-2 rounded-lg px-2 hover:bg-slate-50"><input type="checkbox" wire:model.live="calendarLevelIds" value="{{ $level->id }}" class="size-5 rounded border-slate-300 text-emerald-700"><span class="text-sm">{{ $level->name }}</span></label>@endforeach</div></fieldset>@endif
            @if($calendarPreview && $calendarPreview['weeks']->isNotEmpty())
                <div class="mt-4 rounded-xl bg-amber-50 p-4 ring-1 ring-amber-200"><p class="font-semibold text-amber-950">Dampak sebelum disimpan</p><dl class="mt-2 grid grid-cols-2 gap-2 text-sm"><div><dt class="text-amber-800">Pekan terdampak</dt><dd class="font-mono font-semibold">{{ $calendarPreview['weeks']->count() }}</dd></div><div><dt class="text-amber-800">Materi bergeser</dt><dd class="font-mono font-semibold">{{ $calendarPreview['item_count'] }}</dd></div><div><dt class="text-amber-800">Materi terkunci</dt><dd class="font-mono font-semibold">{{ $calendarPreview['locked_count'] }}</dd></div><div><dt class="text-amber-800">Kekurangan slot</dt><dd class="font-mono font-semibold">{{ $calendarPreview['shortages']->count() }}</dd></div></dl>
                    @if($calendarPreview['shortages']->isNotEmpty())<p class="mt-3 text-sm font-medium text-red-800">Minggu efektif tidak cukup. Sesuaikan rentang semester sebelum menyimpan.</p>@elseif($calendarPreview['item_count'] > 0)<label class="mt-3 flex min-h-11 items-center gap-3"><input type="checkbox" wire:model="calendarConfirmImpact" class="size-5 rounded border-amber-400 text-emerald-700"><span class="text-sm font-semibold text-amber-950">Saya menyetujui pergeseran materi, termasuk yang terkunci.</span></label>@endif
                </div>
            @endif
            <button type="submit" wire:loading.attr="disabled" wire:target="saveCalendarEvent" class="button-primary mt-4"><span wire:loading.remove wire:target="saveCalendarEvent">Simpan dan aktifkan rentang</span><span wire:loading wire:target="saveCalendarEvent">Menyimpan…</span></button>
        </form>
    </div>
    <div class="border-t border-slate-200 p-4 sm:p-5">
        <h3 class="font-semibold text-slate-950">Rentang aktif</h3><div class="mt-3 grid gap-3 lg:grid-cols-2">@forelse($calendarEvents as $event)<article class="rounded-xl border border-slate-200 p-4"><div class="flex items-start justify-between gap-3"><div><span class="status status-warning">{{ app(\App\Services\AcademicCalendarService::class)->typeLabel($event->type) }}</span><h4 class="mt-2 font-semibold text-slate-950">{{ $event->title }}</h4><p class="mt-1 font-mono text-xs text-slate-600">{{ $event->starts_on->format('d/m/Y') }}–{{ $event->ends_on->format('d/m/Y') }}</p></div><div class="flex gap-2"><button type="button" wire:click="editCalendarEvent({{ $event->id }})" class="button-secondary">Edit</button><button type="button" wire:click="deleteCalendarEvent({{ $event->id }})" wire:confirm="Hapus rentang ini? Materi tidak akan ditarik mundur otomatis." class="button-secondary text-red-700">Hapus</button></div></div>@if($event->details)<p class="mt-3 text-sm text-slate-600">{{ $event->details }}</p>@endif<p class="mt-2 text-xs font-medium text-slate-500">{{ $event->applies_to_all ? 'Semua jenjang' : $event->levels->pluck('name')->implode(', ') }}</p></article>@empty<p class="rounded-xl bg-slate-50 p-5 text-sm text-slate-600 ring-1 ring-slate-200">Belum ada rentang libur, evaluasi, atau ujian.</p>@endforelse</div>
    </div>
</section>
