<section id="calendar-detail" class="panel scroll-mt-4 overflow-hidden" aria-labelledby="calendar-detail-title">
    <div class="flex flex-col gap-3 border-b border-slate-200 p-4 sm:flex-row sm:items-start sm:justify-between sm:p-5">
        <div><p class="text-sm font-semibold text-emerald-700">Kalender {{ $plan->academicYear->label }}</p><h2 id="calendar-detail-title" class="mt-1 text-xl font-semibold text-slate-950">Atur waktu semester, libur, evaluasi, dan ujian</h2><p class="mt-1 max-w-3xl text-sm text-slate-600">Rentang yang menyentuh sebagian pekan membuat satu pekan penuh non-efektif. Materi bergeser setelah Admin mengonfirmasi dampaknya.</p></div>
        <button type="button" wire:click="showDetail('')" class="button-secondary">Tutup pengaturan</button>
    </div>
    <div class="grid gap-5 p-4 xl:grid-cols-2 sm:p-5">
        <form wire:submit="saveSemesterRanges" class="rounded-xl bg-slate-50 p-4 ring-1 ring-slate-200">
            <h3 class="font-semibold text-slate-950">Rentang semester fleksibel</h3><p class="mt-1 text-sm leading-6 text-slate-600">Jumlah minggu mengikuti tanggal Admin. Jika rentang dipendekkan, beberapa materi digabung berurutan pada minggu efektif yang sama tanpa dipindahkan ke semester lain.</p>
            <div class="mt-4 grid gap-3 sm:grid-cols-2">
                <label class="grid gap-1 text-sm font-medium text-slate-700">Mulai Semester 1<input type="date" wire:model.live="semesterOneStart" data-validation-field="semesterOneStart" class="min-h-11 rounded-xl border border-slate-300 bg-white px-3">@error('semesterOneStart')<span class="text-sm font-medium text-red-700" role="alert">{{ $message }}</span>@enderror</label>
                <label class="grid gap-1 text-sm font-medium text-slate-700">Akhir Semester 1<input type="date" wire:model.live="semesterOneEnd" data-validation-field="semesterOneEnd" class="min-h-11 rounded-xl border border-slate-300 bg-white px-3">@error('semesterOneEnd')<span class="text-sm font-medium text-red-700" role="alert">{{ $message }}</span>@enderror</label>
                <label class="grid gap-1 text-sm font-medium text-slate-700">Mulai Semester 2<input type="date" wire:model.live="semesterTwoStart" data-validation-field="semesterTwoStart" class="min-h-11 rounded-xl border border-slate-300 bg-white px-3">@error('semesterTwoStart')<span class="text-sm font-medium text-red-700" role="alert">{{ $message }}</span>@enderror</label>
                <label class="grid gap-1 text-sm font-medium text-slate-700">Akhir Semester 2<input type="date" wire:model.live="semesterTwoEnd" data-validation-field="semesterTwoEnd" class="min-h-11 rounded-xl border border-slate-300 bg-white px-3">@error('semesterTwoEnd')<span class="text-sm font-medium text-red-700" role="alert">{{ $message }}</span>@enderror</label>
            </div>
            @if($semesterPreview && $semesterPreview['valid'])
                <div class="mt-4 rounded-xl bg-white p-3 ring-1 ring-slate-200" aria-live="polite">
                    <p class="text-sm font-semibold text-slate-950">Dampak rentang untuk {{ $plan->level->name }}</p>
                    <div class="mt-2 grid gap-2 text-sm sm:grid-cols-2">
                        @foreach($semesterPreview['semesters'] as $number => $impact)
                            <div class="rounded-lg bg-slate-50 p-3">
                                <p class="font-semibold">Semester {{ $number }}: {{ $impact['old_weeks'] }} → {{ $impact['new_weeks'] }} minggu</p>
                                <p class="mt-1 text-slate-600">{{ $impact['items_affected'] }} materi terdampak · {{ $impact['locked_affected'] }} terkunci · {{ $impact['combined_groups'] }} kelompok digabung</p>
                            </div>
                        @endforeach
                    </div>
                    <p class="mt-2 text-xs leading-5 text-slate-600">Materi tetap berada di semester yang sama. Target progres dibagi ulang dan pengisi matriks dijalankan setelah penyimpanan.</p>
                </div>
            @elseif($semesterPreview)
                <p class="mt-4 rounded-xl bg-red-50 p-3 text-sm font-medium text-red-800 ring-1 ring-red-200" role="alert">Lengkapi tanggal secara berurutan. Semester 1 dan 2 tidak boleh bertumpang tindih.</p>
            @endif
            <button type="submit" wire:loading.attr="disabled" wire:target="saveSemesterRanges" class="button-secondary mt-4"><span wire:loading.remove wire:target="saveSemesterRanges">Simpan rentang semester</span><span wire:loading wire:target="saveSemesterRanges">Menyimpan…</span></button>
        </form>
        <form wire:submit="saveCalendarEvent" class="rounded-xl bg-white p-4 ring-1 ring-slate-200">
            <div class="flex items-center justify-between gap-3"><h3 class="font-semibold text-slate-950">{{ $calendarEventId ? 'Edit' : 'Tambah' }} rentang kegiatan</h3>@if($calendarEventId)<button type="button" wire:click="resetCalendarForm" class="min-h-11 text-sm font-semibold text-emerald-700">Batal edit</button>@endif</div>
            <div class="mt-4 grid gap-3 sm:grid-cols-2">
                <label class="grid gap-1 text-sm font-medium text-slate-700">Jenis<select wire:model.change="calendarType" data-validation-field="calendarType" class="min-h-11 rounded-xl border border-slate-300 bg-white px-3"><option value="holiday">Libur</option><option value="religious_holiday">Hari Raya</option><option value="evaluation">Evaluasi</option><option value="exam">Ujian</option></select>@error('calendarType')<span class="text-sm font-medium text-red-700" role="alert">{{ $message }}</span>@enderror</label>
                <label class="grid gap-1 text-sm font-medium text-slate-700">Judul<input type="text" wire:model.blur="calendarTitle" data-validation-field="calendarTitle" class="min-h-11 rounded-xl border border-slate-300 bg-white px-3" placeholder="Contoh: Ujian semester serentak">@error('calendarTitle')<span class="text-sm font-medium text-red-700" role="alert">{{ $message }}</span>@enderror</label>
                <label class="grid gap-1 text-sm font-medium text-slate-700">Tanggal mulai<input type="date" wire:model.change="calendarStartsOn" data-validation-field="calendarStartsOn" class="min-h-11 rounded-xl border border-slate-300 bg-white px-3">@error('calendarStartsOn')<span class="text-sm font-medium text-red-700" role="alert">{{ $message }}</span>@enderror</label>
                <label class="grid gap-1 text-sm font-medium text-slate-700">Tanggal akhir<input type="date" wire:model.change="calendarEndsOn" data-validation-field="calendarEndsOn" class="min-h-11 rounded-xl border border-slate-300 bg-white px-3">@error('calendarEndsOn')<span class="text-sm font-medium text-red-700" role="alert">{{ $message }}</span>@enderror</label>
                <label class="grid gap-1 text-sm font-medium text-slate-700 sm:col-span-2">Keterangan detail<textarea wire:model="calendarDetails" data-validation-field="calendarDetails" rows="3" class="rounded-xl border border-slate-300 bg-white px-3 py-2" placeholder="Keterangan yang akan tampil pada preview dan Excel"></textarea>@error('calendarDetails')<span class="text-sm font-medium text-red-700" role="alert">{{ $message }}</span>@enderror</label>
            </div>
            <label class="mt-3 flex min-h-11 items-center gap-3 rounded-xl border border-slate-200 px-3"><input type="checkbox" wire:model.live="calendarAllLevels" class="size-5 rounded border-slate-300 text-emerald-700"><span class="text-sm font-medium text-slate-700">Berlaku untuk semua jenjang</span></label>
            @if(! $calendarAllLevels)<fieldset class="mt-3" data-validation-field="calendarLevelIds" tabindex="-1"><legend class="text-sm font-medium text-slate-700">Pilih jenjang</legend><div class="mt-2 grid max-h-44 gap-1 overflow-y-auto rounded-xl border border-slate-200 p-2 sm:grid-cols-2">@foreach($levels as $level)<label class="flex min-h-11 items-center gap-2 rounded-lg px-2 hover:bg-slate-50"><input type="checkbox" wire:model.live="calendarLevelIds" value="{{ $level->id }}" class="size-5 rounded border-slate-300 text-emerald-700"><span class="text-sm">{{ $level->name }}</span></label>@endforeach</div>@error('calendarLevelIds')<p class="mt-1 text-sm font-medium text-red-700" role="alert">{{ $message }}</p>@enderror</fieldset>@endif
            <p wire:loading wire:target="calendarTitle,calendarStartsOn,calendarEndsOn,calendarAllLevels,calendarLevelIds,calendarConfirmImpact,refreshCalendarImpact" class="mt-4 rounded-xl bg-sky-50 p-3 text-sm font-semibold text-sky-900 ring-1 ring-sky-200" role="status">Menghitung dampak dan menyinkronkan formulir...</p>
            @if($calendarPreview && $calendarPreview['ready'])
                <div class="mt-4 rounded-xl bg-amber-50 p-4 ring-1 ring-amber-200" aria-live="polite"><p class="font-semibold text-amber-950">Dampak sebelum disimpan</p><dl class="mt-2 grid grid-cols-2 gap-2 text-sm sm:grid-cols-3"><div><dt class="text-amber-800">Pekan non-efektif</dt><dd class="font-mono font-semibold">{{ $calendarPreview['week_count'] }}</dd></div><div><dt class="text-amber-800">RPP terdampak</dt><dd class="font-mono font-semibold">{{ $calendarPreview['plan_count'] }}</dd></div><div><dt class="text-amber-800">Materi pada rentang</dt><dd class="font-mono font-semibold">{{ $calendarPreview['item_count'] }}</dd></div><div><dt class="text-amber-800">Total materi bergeser</dt><dd class="font-mono font-semibold">{{ $calendarPreview['moved_count'] }}</dd></div><div><dt class="text-amber-800">Materi terkunci bergeser</dt><dd class="font-mono font-semibold">{{ $calendarPreview['shifted_locked_count'] }}</dd></div><div><dt class="text-amber-800">Kelompok digabung</dt><dd class="font-mono font-semibold">{{ $calendarPreview['combined_groups'] }}</dd></div></dl>
                    @if($calendarPreview['shortage_count'] > 0)<p class="mt-3 text-sm font-medium text-red-800">Acara ini membuat semester tanpa minggu efektif. Kurangi rentang acara atau perpanjang semester.</p>@elseif($calendarPreview['requires_confirmation'])<label class="mt-3 flex min-h-11 items-center gap-3"><input type="checkbox" wire:model.live="calendarConfirmImpact" data-validation-field="calendarConfirmImpact" class="size-5 rounded border-amber-400 text-emerald-700"><span class="text-sm font-semibold text-amber-950">Saya menyetujui pergeseran/penggabungan materi, termasuk yang terkunci.</span></label>@error('calendarConfirmImpact')<p class="mt-1 text-sm font-medium text-red-700" role="alert">{{ $message }}</p>@enderror@endif
                </div>
            @endif
            <button type="submit" wire:loading.attr="disabled" @disabled(! $calendarSubmitReady) class="button-primary mt-4 disabled:cursor-not-allowed disabled:opacity-60"><span wire:loading.remove wire:target="saveCalendarEvent">Simpan dan aktifkan rentang</span><span wire:loading wire:target="saveCalendarEvent">Memperbarui {{ $calendarPreview ? $calendarPreview['plan_count'] : 0 }} jenjang...</span></button>
        </form>
    </div>
    <div class="border-t border-slate-200 p-4 sm:p-5">
        <h3 class="font-semibold text-slate-950">Rentang aktif</h3><div class="mt-3 grid gap-3 lg:grid-cols-2">@forelse($calendarEvents as $event)<article class="rounded-xl border border-slate-200 p-4"><div class="flex items-start justify-between gap-3"><div><span class="status status-warning">{{ app(\App\Services\AcademicCalendarService::class)->typeLabel($event->type) }}</span><h4 class="mt-2 font-semibold text-slate-950">{{ $event->title }}</h4><p class="mt-1 font-mono text-xs text-slate-600">{{ $event->starts_on->format('d/m/Y') }}–{{ $event->ends_on->format('d/m/Y') }}</p></div><div class="flex gap-2"><button type="button" wire:click="editCalendarEvent({{ $event->id }})" class="button-secondary">Edit</button><button type="button" wire:click="deleteCalendarEvent({{ $event->id }})" wire:confirm="Hapus rentang ini? Materi tidak akan ditarik mundur otomatis." class="button-secondary text-red-700">Hapus</button></div></div>@if($event->details)<p class="mt-3 text-sm text-slate-600">{{ $event->details }}</p>@endif<p class="mt-2 text-xs font-medium text-slate-500">{{ $event->applies_to_all ? 'Semua jenjang' : $event->levels->pluck('name')->implode(', ') }}</p></article>@empty<p class="rounded-xl bg-slate-50 p-5 text-sm text-slate-600 ring-1 ring-slate-200">Belum ada rentang libur, evaluasi, atau ujian.</p>@endforelse</div>
    </div>
</section>
